### Variables
@host = localhost
@port = 3999
@token = "<< insert your bearer token here >>"

### SCIM: GET /Users
GET http://{{host}}:{{port}}/Users
Authorization: Bearer {{token}}
Accept: application/scim+json

### SCIM: GET /Groups
GET http://{{host}}:{{port}}/Users
Authorization: Bearer {{token}}
Accept: application/scim+json

### SCIM: GET /ServiceProviderConfig
GET http://{{host}}:{{port}}/ServiceProviderConfig
Authorization: Bearer {{token}}
Accept: application/scim+json

### SCIM: GET /ResourceTypes
GET http://{{host}}:{{port}}/ResourceTypes
Authorization: Bearer {{token}}
Accept: application/scim+json
